### ISSUE TITLE
Large memory leaks still occurring

### ISSUE THREAD

**Issue by source83** [janusvr/janus-server#46]
During the Vinesauce stream today/night, there were a LOT of people in janus.
I was watching the pm2 server status and bandwidth while it was going on.
The memory for the server kept increasing pretty fast and causing it to restart multiple times.
At the moment, the server has restarted 11 times, it's currently been up for 32 min and is back up to 1.249 GB of memory..
There must be some nasty memory leak somewhere.
I don't have experience with how to debug this sort of thing so I can't help with it, sorry.

**Comment by sirkitree** [comment]
Last time it was the way James was moving data through and I think it was not being deallocated (positional data i think).

**Comment by source83** [comment]
It looks like there is data for the users that isn't deallocated/deleted since after the user count dropped down to 5-8 (from 40-50) it was still up over 1gb.

**Comment by bnolan** [comment]
Do we have any test scripts that can simulate a janus client? Then we could use some node profiling to find where the leaks are.

**Comment by sirkitree** [comment]
We don't. And quite frankly, the janus client changes so rapidly that keeping something like this up to date might just be an exercise in frustration.

**Comment by source83** [comment]
True, but the memory problem has been present for as long as I've been messing with the presence server code.  
There's possibly exceptions that aren't being handled or some data that's not getting cleared upon client exit.  
In any case, it needs to be addressed in some way.

**Comment by timschwartz** [comment]
If you could modify one of the rooms to use my janus-server it would let me collect some debug data.

Can you add *server="metaverse.host" port="5567"* to the <room> tag of some room that gets a moderate amount of traffic?

**Comment by oculushut** [comment]
Would it help to run some tests like this help? 

https://github.com/janusvr/janus-server/issues/13#issuecomment-90078736

**Comment by timschwartz** [comment]
Sure.

**Comment by oculushut** [comment]
Have my test rig setup again with current release + modifications.  Found that some of my previous tests were actually doing a Denial of Service attack on the server and it was actually crashing out or at least I could not be confident that it was processing properly "under the hood".  

I've now made some changes to the code to allow me to log in "verbose" mode so I can sanity check  that a test is likely to work before switching the logging back down to "info" mode to run an actual test.  

The tests take a long time to run and I can't really leave the PC running at night at the moment :P  So I'll post results here as they come up:

# TEST 1 -> (Move()x1000 a sec) for 2hrs 46min+

## Conclusion

Move() is not showing signs of memory leaks in this test - or at least any leaks are being cleared up due to some of the other actions in the test (e.g. CONNECT/DISCONNECT/logon/enter_room).  Noted that when I looked at the JanusVR client it actually passes avatar data every few move calls.  I did not simulate this.  Additionally, the number of move calls is likely to be much greater.  May be worth doing a test with more Move() calls.  My original test with 1 million move calls caused the server to hang earlier.

I may ramp up the test to 10K or 100K move() calls tomorrow.  Or may move onto some of the other functions.  Let me know if you have preference.

## Test Details

Do the following loop for 2hrs 46mins+

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"enter_room", "data": {"roomId": "01428c2908cc9b454a3d10af3e8975fb" }}
{"method":"move", "data": [0,0,0,0,0,0,0]} x 1000
DISCONNECT

![Test 1](http://i.imgur.com/mAbwMzT.jpg)

**Comment by oculushut** [comment]
What version of NodeJS is being used on the production server?

**Comment by timschwartz** [comment]
v0.13.0-pre

**Comment by oculushut** [comment]
I'm currently on **Node v0.10.40**.  Pretty out of date.

Hope this doesn't cause any differences in test result.  I'm just in the middle of another test.  May try and upgrade to match your version after the next batch of tests...

And just for completeness, the VM I am using:

> [vagrant@oculushut-janus janus_server]$ cat /etc/centos-release
> CentOS Linux release 7.1.1503 (Core)

**Comment by oculushut** [comment]
OK, I convinced my wife that it was important to leave the PC running all day and all night... so here are some results from Test 2.  Will not do anymore tests on move().

# TEST 2 - Move() function call x100K 8 times

## Conclusion

I am now pretty sure that there is no memory leak in the move() function.  If there is one then it is not big enough to show growth over 100K calls to move().  Noted that this test highlights the fact that the number of calls that each client is likely to make, the size of those messages and the rate at which the server can process the queue has a direct impact on the memory requirements for the server.  I do not currently understand why the memory usage is more erratic at the begging of each load and then dies down.  Note that the CPU reading is: 

"...currently expressed as the percentage of time spent running during the entire lifetime of a process."

## Test Details

Sent the following 8 times (total of 800K move() calls processed).  Do not start next iteration until previous queue appears to have been processed.  This should be indicated by stable CPU usage.

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"enter_room", "data": {"roomId": "01428c2908cc9b454a3d10af3e8975fb" }}
{"method":"move", "data": [0,0,0,0,0,0,0]} x 100K
DISCONNECT

![Test 2](http://i.imgur.com/bGLsuvW.png)

**Comment by sirkitree** [comment]
Very cool man! What's the next thing on your list to test?

**Comment by oculushut** [comment]
Gonna hit subscribe() now... hopefully have something for you guys tomorrow or very late tonight!

**Comment by oculushut** [comment]
# TEST 3 - Subscribe() function call x20K at 10 Minute Intervals

## Conclusion

This test had to be abandoned on the 8th iteration.  It looks like my server could not clear down the queue within 10 minutes.  It looks like the queue built up and the system ran out of memory and started to page.  Then it went super slow... it did not crash though.  Just seemed to go slow.  

I am assuming that the increase in memory is just caused by the build up of the message queue.

In hindsight, this set of tests feel unrealistic given the likely volumes of subscribe() calls.  Will document them anyway though since they've been ran.  They probably serve to prove that the "simpleset" library can handle some basic operations.  I.e. subscribing to the same room over and over again with the same user does not increase the set.

## Test Details

Send the following

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"subscribe", "data": { "roomId": "01428c2908cc9b454a3d10af3e8975fb" }} x 20K
DISCONNECT
WAIT 10 MINUTES AND REPEAT 10 TIMES (Abandoned on 8th iteration)

![Subscribe Calls](http://i.imgur.com/u7jkDa3.png)

**Comment by timschwartz** [comment]
What cpu and how much ram does your server have?

**Comment by oculushut** [comment]
# TEST 4 - Subscribe() function call x20K at 20 Minute Intervals

## Conclusion

No signs of Subscribe() leaking in this test.  20 minutes was enough time for my server to clear down the queue.  After 10 iterations (i.e. 10 x 20K subscribe calls), the %mem settled down at around 20%.  I wanted to see if the amount of memory the node process settled at would increase if I increased the number of calls so ran one more test after this.

## Test Details

Send the following

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"subscribe", "data": { "roomId": "01428c2908cc9b454a3d10af3e8975fb" }} x 20K
DISCONNECT
WAIT 20 MINUTES AND REPEAT 10 TIMES

![Subscribe Calls](http://i.imgur.com/2aP9bg1.png)

**Comment by oculushut** [comment]
# TEST 5 - Subscribe() function call x30K at 30 Minute Intervals

## Conclusion

Peak memory usage was higher, but this was expected since queue should be bigger.  No signs of Subscribe() leaking in this test either.  Memory settled down to around 20% again even after I increased each batch by 10K extra subscribe() calls compared to previous test (total calls = 30K x 10 iterations).  30 minutes was enough time for my server to clear down the queue after each iteration.  Will either move on to another function after this or else do some more "realistic" tests (e.g. more than 1 connection).  Not sure yet.  Suggestions welcome!

## Test Details

Send the following

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"subscribe", "data": { "roomId": "01428c2908cc9b454a3d10af3e8975fb" }} x 30K
DISCONNECT
WAIT 30 MINUTES AND REPEAT 10 TIMES

![Subscribe Calls](http://i.imgur.com/Qr3UOVl.png)

**Comment by oculushut** [comment]
@timschwartz this is the VirtualBox VM (1xCPU and 512MB RAM):

![VirtualBox](http://i.imgur.com/CCsJYur.png)

This is the CPU of my physical PC.  Most of the activity is on VirtualBox.  The actual VirtualBox process reported around 12% activity, but there are other processes running which may also belong to VirtualBox which are making up the rest of the CPU utilisation.  I've not checked properly.

![Base Box CPU](http://i.imgur.com/nalY2RR.png)

There is plenty of RAM in the base box (32GB) so I don't think things I do on my desktop usually will affect the tests too much.

![Base Box RAM](http://i.imgur.com/zebPTm0.png)

Other than that... I have a few things running on the VM... the Node server, mysqld as required, 1 script to log %cpu and %mem and I am usually tailing server.log file and the %cpu/%mem log file.

**Comment by oculushut** [comment]
# TEST 6 - users_online() function call x 30K at 30 Minute Intervals

## Conclusion

No obvious memory leak with users_online() when just doing basic call.  Memory usage settled at around 20% at the end of the test.

## Test Details

Send the following

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}
{"method":"subscribe", "data": { "roomId": "01428c2908cc9b454a3d10af3e8975fb" }}
{"method": "users_online", "data": {"maxResults": 50, "roomId": "01428c2908cc9b454a3d10af3e8975fb"}} x 30K
DISCONNECT
WAIT 30 MINUTES AND REPEAT 10 TIMES

![Subscribe Calls](http://i.imgur.com/N1wW51X.png)

**Comment by oculushut** [comment]
# TEST 7 - portal() function call x 30K at 30 Minute Intervals

## Conclusion

No obvious memory leak with portal() when just doing basic call - same call each time.  I changed the way I submitted on this test.  Test harness is too quick now.  I had to slow down the submissions and introduced a 10ms delay between each call.  The end of the graph shows the memory usage going through the roof when I switch off the throttling...

ON A COMPLETELY SEPARATE NOTE: May go back to the "move" function next... I had a look at what the server was broadcasting and it looks like there is LOTS of data being passed for voice.  Perhaps there is no memory leak and there's just a lot of memory required of the processor cannot de-queue quick enough?  E.g. this kind of thing looks like it could get bulky if the voice data is being expanded out to base64 for transmission... (captured earlier today - did not try decoding to see what was in there):

```
{"method":"user_moved","data":{"roomId":"a8e6a1e4c38a37a2ab71aef757ebff90","userId":"Mysteryrune","position":{"pos":"-2
.90738 0.0499145 15.5611","dir":"0.581825 -0.0764857 -0.80971","view_dir":"0.581815 -0.0767104 -0.809696","up_dir":"0.0
447631 0.997053 -0.0622956","head_pos":"0 0 0","speaking":"true","audio":"hgR7BPgDvgJBAe//Bv4X/VH9u/zl/Jz8aPv3+2j+8wBbA
30G8AhbCy4PGxHKDysM6QbeARz/z/x9+Lbzpe+c7bzwT/fs/EEBGQOGARMCpgZ9CvwMFw54CxgIsgb9A/wAH/9T/Pb5IPla+Kb3G/ds9Vrzc/PN9cf4Nvuc
/VT/2f/NAcED2QShBowHnwa0BVoEdwEv/1D95ft5/Er91vxS/K78g/6oASIGCwpjDM0PDhPPEjIPpAliBK8BZP/a+e7yKe0m6nHtM/UM/BcBaANKASEBvQU
mC3oQshIuEO0MQwqOBuoDGAJs/gH7PPgF9gH1PfR38grxiPFp9Fn4Mft5/Tr+M/+lASMERQauB/wHQQdTBo4EDQIfACL+lPw5/Nf7B/sI+r75VftP/4EEbg
kQDoMRBBSOE/wNBQi+A3IBLv+W+AXvEecJ5KboRPRg/ioDfANS/3j/ygaMDgMVWBdDE7UNKwr4BbwCxQCN/If4ovXZ8gjx7e+S7p3uTfH59ff6Vv4W/xj+o
P4jAoYGYAkhCiEI8AS6At4BsQHjACP/ufyP+u753vm2+QP7Of6xAt8HiQzwD84TdxV7EBIKHgaxA28Cl/xf8Enlhd9h4eDtKfxBAvECJ/5r+iQDzxCmGtEf
DhsQEKEJzwV6AxIFIwO6/Ev3DvH26+/qmerY6wXxzPYU+6/94PxJ+5T+CwW+C2AQrA6ZBxMBnv4f/zkCfwN//wv7EffE9Gb2DPka+8H+lwOUB58MBhGEFGk
XvxNSDHIHhwTWAg7+TfHM4sDb+9xN6ST6ZgEaASD8zfac/j8Qvh1ZJBwgixHrB/kFlwX3CDgIpf7C9Rbv5+mT6pfst+yA8Hf1Cfh7+mT7hfrH/qQHlQ7lEt
AQQQivAaMAKgNlBlAGp//D91HzuvJA9v754voZ+0D9DwKKCc4QkRZGGngWvw0QCHkFAAUZAqT1kuVo3GXbDeaB94v+I/1e+UD0kPzYEK4ediPnHmIQKgcsB
9EJ1gwwC2wAnvQa7frob+qi7srvevE69G/2IPkk+wL8fv9QB+oMBRAnDjQHxAG/AcAEkgcpBhj/8vfl9Kj0MPlX+8L5SfnR+sz/jQdfDz8UERjjFQsMGgYj
BXcFAAXn+WToId0V28LkwfdTAPf8hvdd8Xz4lQ0JHX0hpxzUDaEDBAZ/CogOuA0EAYvzeOyX6RXtPPPv8sXxovKt8iv2Fvsx/vIB+gdXC3MLTgoRB24FNAf
CCO0HKAQm/bL29/W797n5+vqL+JH3sPsgAksJdBAmFPoWCBekDvYHVgYPBRADL/kj6PTc3dt55Or2DQG7/Cz3C/Jp+F8PvyCaI5ocuAvD/2cFcAxfD4oNif
4t7+Tq0Ouh8EX3C/aq8avwrfCi9NP8pgGiAz4HDggKBzcIHwgFCL0JBwkDBS4Cef7B+pv7XPpN+Fj3yPWk9+n91AMKCNoMWRBeFa4XEhC3CA0FyQMaBLX6L
+ky3UfbFuWX+eIBZ/t59Vnv8/i/Eiwi+iLlGSsIrACICqcRyBLkDKP6qexP6xTutfMC+Nryluya7M/vM/fNABgE6gJsBAgFZQaoCgMMFgsBCncGNAKlAnQB
Pv82/3L7mPjN+O35Ff30AZAEQwYDC7kQvxhbGvcP4wYCA7MDSAZ//I3pi91N223mV/ylA6j7wPSH7rn5qxQNIsIgiBZ/BMf/pAyrEzETPgvg9yzs/+2s8ST
2mvfO77Tpluv478j3EgAtAWj/dQFhAwEHpwynDYQL9AgfBecB1wOUA58AZP7T+FX1Tvft+sX+dALWAh0EagrfEpcbFBqKDPECyQAxBQgI0vrL5svbMtui6v
b/DgHZ9wTxy+xc/6EauSEPHTEQqP90ArIRmBT0EHIEzfC86zrxRfUT+EH1Ouwc6aLtf/On+4cBV/8t/aP/9wITCbYOCA7YCUYGQAI/AoMGpwVGAm39svcq9
2T76f+EAQoBmP+8AvIKCxWTG+ESRAXf/18BKQnYB7H0teLp21fgqPVsBHv7C/NN7SLwHgs8HycdyRWGB3z9OgtMGFYVaA77/H7tyfA+95X5Tfp48jrpXeqA
8IH3Pv8QAYj8vPsC/5ID4QoCDzcMBgejAskA+APrBxAGagCg+Cb0NPfx/N0AxAFk/67+OwRfDR0YDB3bEbAD3f9yAtwKagl09LThztvn4BH3KwbC+wLyIOy
47rwJMB6QG3YUlgcI/ioL0BZIExUNIf1H7oDx7fYV+D75uPLk6UTrGPAd9Xb8uv3++RD76P6DAyUL0w4dCzUHvAM5ArAGOgm6BVb/Mvgj9bf5fP/QATQBt/
0O/tEF6w9dGYUZmAr2/7EASgZWDiQFYu3E3wPeDelKAecFdPZG71/qC/YLFGcdxBVRDWj/Rf/YEWkXsRHHCL71OO4V9gr54Pkh+IHteOji7MXx5/jP/9f8B
vkx+6b+aQexDtEPCwoDBIEAMAPfCbQJ3QPh+7P1DvbO/GEBKANoAA/8t/4MCOYRSRruFksGvP6bAFUI6Q8CA4Hrpt8V4KHt0AX+BdH1ru906tP4jhWCHGoU
oAuj/UgAZBPjFY8QXwer9YLx2vi7+tz6CPj/7LDn3esK8S/5qf5O+rT2uvnf/gUJmhGnD2kJ2QMvAWgGmgynCeUBEPmq8xf4lwAbA64Bo/wP+en/wQqXFBo
amxAh/9P8ZQIZDBkPq/wf5d3eDuOK9Y8JjwCR8jbr/OtYAVUcLx29DzMFkv2UCO8UhhIXDIv+bPJs77L6Ovzu+sr1vOky53bqavYI/qEBOvrA9iH7iwFuDr
IThw11A1v+TAOJDPMPxQcZ/K/zbfU1Ar8KjQcmAAL5+PeHAsYN9xS9FgwKrPi++mkEOA3rDoz3C+Sq4SboGfyiCpj+dfGw7mrsWAUCGyYU9wv9/zb3Zga4F
vIT8A3f/0TwV/Po+fL6ivt+8S7mmeiW8gj5af3Y+171yPkiAgMLCREmDpMGqgQrB6QKbA1eCT0AEPvn+t7+9gSOBGP/MPyh+zn/bgk4EHYS1g/xAWb8QQNM
CaoOtgP/6zbiW+cn8/wHhQaK80vvGe/S/T8agB3KDgEFI/lI/pcTJBcuDS0DHvJR73L7V/4l+0z2YupD6LzxXfVy+4cA5Ptq+zYAfwKCCXgO9gn7BdECWAA
RBmAM0gruBEf+evmv/TcEogRBAVr82vkxAUgMghEcEIYCcPme/xAIIAxIAwPtFOLo5/n08gbEBeLy6upz7ZH9OhdZGn4LJgAq+RIBYxOCFnQMpv6L8a/x6P
pm/nP8Gfbe7ObpP+/O9ub8GwBJ/Rn6vfs4AfgIFA7zC9QDxf3Q/foDoAvjCjUCTvow+QD/OQdGCQ0DWf62/ioFzA7ADVUAufiA+tsBowkI/kTqPeQQ6Bb5K
A0LBvL0O+7G7jsE/x12G2EMV/7M9BwBGxRbFX4K3/iF6C3sk/oaAj0B+vX16GjsgPozBksMIQbK+rD5CwBnCMcOkAkPAP/9ZQAnBh8M9gmuA9cBBwK0A8UH
BQe4A5QEDQV2B7cLCwaD/En8qv1zAqsENPa16mLrv+8RAGQKkv599nL04/ZgCu8WHBA/CHYAz/4cCSINtAXT/h34bfQt+GL3V/Mz9cj2nfmP/pz8yPh8/AY
BfgWoCb4FvwCuAskFIgnjCzQHiwEJAvUCVARlBroD2wBGAv4CJAUHCdcIFwf1AGn61PxgApYEFP2W68vjsOg19VgHjAhD+bXwzPBb//kWnhySD9r/hPZA+1
IJpQ69B7n7ovBC7RX0kfwuABb+TvdH8vjzPvv/ArwG6AOa/FL6/P/uBkELvgleAun+LgPaCC4L4Qfe/0T8fP8EBNcHFQihA7oB4wOnAN79Bv8Y/if/l/qt7
Ljoeuy29O4DpwSF+S739fgDBKkVDxZ6CQYAhPj5+x4JFQryAKL2QO038AD+kwTtAnv9w/Re9ar/kwW3BFz/gffY96EBAgl3C48HLgB6ANwHnA11ECINmgPt
/54C4wTdB/oGYwDA/xwCNv5W/aj9kPu2/qH8bvIv79DvwfYSBZUHZ/6t+DL6OgOQEcMUjwnA/Sv4j/yUB+0J+P6v84LwZvecAmUFbf779hb1tvqkBE0Ggf+
8+K/2M/0DB3wJBwX3/9P9/gIkCpgL4AcMAZ/7a/0IAjUE0wTUALX75vzfATUFnAR2/4H7gfwF/6L9Mvko9iX1U/kk/yT/7/wv+7/8XAOwBgQENP8l/I/+RQ
M4A1UAWv04/A4ACgSnAnj+t/vP+in98f+//Tn6GfrH+xEAKgRuA8YCqQP8A+YFzQdNBsgEHgNjALD/r/8f/gP9RfwD/PP9S/4x/X/9if06/wIBCwAh/mP7/
fkD/L//agHHAMz+M/2N/iUAPgFLAnAB0v5m/ET7Uv0FAggFpwSnAvn/Jv92ATAEygT8Atr/3/0i/9cAXQGCAeAAEgD4AEsBWAF2AmUDOwMmApEAj/9WAJsB
IwJDAkcAT/7+/nkAUgLFAhIBYv8p/v79jf+DAAQAI/40/Pv69/ux/aP+W/8G/wv+lP0z/s8AYwObAzUCIQB7/7kBIwRdBMkCFgCV/tQAzQOrA+YBEP+//Hb
+cQHZASABgv8r/kUAgQOkBJAEJAMIAQkBMQEEABcApf9q/lf/JwCQ/xgAzf/B/68BngHt/77/AP9E/pn/kP6X+6n6cPqa+xT+G/4S/Rn93P12//IBlgL3AK
gA8gAkAlUEQwTuAY0A8P8lAMkBjwGc/zn+lf2b/lcAOgAf/4P+pP7s/3kBtwGZAPD+G/7z/koAwf93/tr9Bf0O/rX/Sf9E/2//S/9+AEYBx/9K/sb9Qf4m/
7D+l/0F/c78qv28/vf+Pv8BAFYArQDoAFIAogBRAfwAbAG8AUQBDQLIAtgCKQPMAswB9wFgAjcC1QEuAZr/Nf8cADYAgAChAJL/Av+J/5b/7f8+AIf/ov+b
ACUBXwHlACsARgD3AOIAowAgAFn+G/60/gT+av6w/vr9Gv4a/o7+lv++ALQBxQEyAc//WP+HAFMBRwEVAdz/Lf8uAJwBKwPEA80C2gHJAU8CMQOYA8ICLAE
3AML/e//7/w4Asf9S/5z+Wv4z/mf+av+o/7b/df9T/m7+M/+g/1QAJwAW/zr/Q/8o/4v/tP9+/4z/+v5t/u3+Rf9i/4P/+/5E/g7/z//Q/z4AXf+J/m//Ww
DNAIcAxP+K/4cAuwH6AXABwwDz/yIAsgAUAIv/Bf9n/qP+lv5l/sP+BP/f/4YAw/+G/sH9of17/Sr9/vzQ/Pb8a/22/fn9NP7c/nT/p/8dAFsA+v+J/1n/u
f+KAHABkgE3APr+xf6g/xUBqAFOAGj+v/2J/o8AzgHSAOr+D/73/u8AewKzAfL/ev+2//kAcwICAqkAhf8T/zgA8wBmAMT/sP4G/sv+n/+P/yH/Uv6U/Ur+
gv+c/3r/Vv8T/7z/7gDJAA4AV/+z/hT/8v9hABIAu//n/+UABAJEAukBiQG3AQ==","_userId":"XXXXXX","_userList":[]}}}
```

## Test Details

Send the following

CONNECT
{"method":"logon","data":{"userId":"${__samplerName}${__threadNum}${__counter(TRUE)}", "version":"39.5","roomId":"01428c2908cc9b454a3d10af3e8975fb"}}

{"method":"portal", "data":{"url":"http://www.AAAAAAAAAA.com","pos":"-7.16883 -0.267702 -6.57243","fwd":"0.967686 0 -0.234104"}} x 30K with 10ms delays

WAIT 30 MINUTES AND REPEAT 10 TIMES
DISCONNECT

![Portal Calls](http://i.imgur.com/pdruOiq.png)

**Comment by timschwartz** [comment]
So does all of this indicate there is nothing really wrong with the server?

**Comment by source83** [comment]
As far as I've seen, there has not been any memory problems as of late.
But, the audio packets do need to be compressed.  
As far as I've understood, this is something that has been put on the TODO list for James and Devlin.
I do believe the memory problem has been solved with James's patch from a few months ago, so this issue might be solved, for now.
